---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaskapp-8277127070-release
  namespace: personal-rnd
spec:
  releaseName: flaskapp-8277127070
  targetNamespace: personal-rnd
  interval: 24h
  chart:
    spec:
      chart: base-deployment
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: crazedencoder
        namespace: flux-system
      interval: 24h
  values:
    global:
      applicationName: flaskapp-8277127070
    replicaCount: 2
    image: registry.crazedencoder.com/8277127070/sample-app:v1
    

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: letsencrypt-ingress-8277127070-flaskapp
 namespace: personal-rnd
 annotations:
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/secure-backends: "true"
  nginx.ingress.kubernetes.io/enable-access-log: "false"
  cert-manager.io/cluster-issuer: letsencrypt-issuer
  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  kubernetes.io/ingress.class: nginx
spec:
 tls:
 - hosts:
   - 8277127070.crazedencoder.com
   secretName: letsencrypt-issuer
 rules:
 - host: 8277127070.crazedencoder.com
   http:
     paths:
     - pathType: Prefix
       path: /
       backend:
         service:
           name: flaskapp-8277127070
           port:
             number: 8001